const IMAGES = {
  meta: '/images/meta.png',
  monkey: '/images/monkey.png',
  logoPortfolio: '/images/logoPortfolio.png',
  headMonkey: '/images/headMonkey.png',
  port: '/images/portImg.jpg',
  p1: '/images/p1.webp',
  p2: '/images/p2.webp',
  p3: '/images/p3.webp',
  p4: '/images/p4.webp',
  p5: '/images/p5.webp',
  p6: '/images/p6.webp',
  p7: '/images/p7.webp',
  p8: '/images/p8.webp',
  p9: '/images/p9.webp',
  p10: '/images/p10.webp',
  p11: '/images/p11.webp',
  p12: '/images/p12.webp',
  p13: '/images/p13.webp',
  p14: '/images/p14.webp',
  p15: '/images/p15.webp',
  s1: '/images/s1.webp',
  s2: '/images/s2.webp',
  s3: '/images/s3.webp',
  s4: '/images/s4.webp',
};

export default IMAGES;
